disabled_rules:
  - trailing_comma
  - opening_brace
  - todo
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Package.swift
  - Tuist
  - Targets/API/Tests
  - Targets/Growatt/Tests
  - Targets/UIFramework/Tests
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
line_length:
  warning: 200
  ignores_comments: true

force_cast: warning # implicitly

force_try:
  severity: warning # explicitly

large_tuple:
  warning: 3
  error: 4

function_body_length:
  warning: 200
  error: 1200

type_name:
  excluded:
    - T

identifier_name:
  excluded:
    - to
    - id
    - ui
    - ts
